application:
  name: simple-example-node
  project: giri-node-example
  cloud_region: aws/eu-west-3
databases:
- type: postgresql
  version: "11"
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /
